# Generated by Django 5.1.7 on 2025-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_venue_venueimage_alter_venue_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
